name: Generate Mascot

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  generate-mascot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Generate Release Mascot
        uses: OwainWilliams/OC.ReleaseMascot@main
        with:
          Tag: ${{ github.event.release.tag_name }}
